### ISSUE TITLE
Configurações de replicado incompletas

### ISSUE THREAD

**Issue by wgnann** [uspdev/starter#7]
Ao proceder com o setup, não configurei o replicado (por ele não ser necessário no projeto). Daí o `php artisan key:generate` falha com `Configurações do replicado incompletas.`.

Uma possibilidade de resolver é documentar a necessidade de se preencher esses campos. Outra é preencher os campos no `.env.example`.

**Comment by masakik** [comment]
se não for usar o replicado, teria de remover ele do composer e remover as configurações do env/env.example.

Acho que documentar esse procedimento deve resolver.
